# Generated by Django 5.2.8 on 2025-11-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_review_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image principale du produit', upload_to='products/%Y/%m/%d', verbose_name='image principale'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/additional/%Y/%m/%d', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='boutique.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'image supplémentaire',
                'verbose_name_plural': 'images supplémentaires',
            },
        ),
    ]
