# Generated by Django 5.2.8 on 2025-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text="Adresse complète de livraison (si différente de l'adresse de facturation).", verbose_name='adresse de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Date à laquelle le client souhaite être livré ou récupérer sa commande.', null=True, verbose_name='date de livraison souhaitée'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Livraison à domicile'), ('pickup', 'Retrait en magasin')], default='delivery', help_text='Choisissez si le client souhaite se faire livrer ou récupérer sa commande en magasin.', max_length=20, verbose_name='mode de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, help_text='Heure à laquelle le client souhaite être livré ou récupérer sa commande.', null=True, verbose_name='heure de livraison souhaitée'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes supplémentaires concernant la commande.', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Lieu où le client souhaite récupérer sa commande.', max_length=255, verbose_name='point de retrait'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Numéro de suivi de la commande (pour les livraisons).', max_length=100, verbose_name='numéro de suivi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('en_preparation', 'En préparation'), ('prete', 'Prête à être récupérée'), ('expediee', 'Expédiée'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('recuperee', 'Récupérée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
    ]
