# Generated by Django 5.2.8 on 2025-12-03 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_order_delivery_address_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='nom de la spécification')),
                ('value', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='boutique.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'spécification technique',
                'verbose_name_plural': 'spécifications techniques',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
