# Generated by Django 5.2.8 on 2025-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='backorder_allowed',
            field=models.BooleanField(default=False, help_text='Si activé, les clients pourront commander même si le stock est épuisé', verbose_name='autoriser les commandes en rupture de stock'),
        ),
        migrations.AddField(
            model_name='category',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Seuil à partir duquel une alerte de stock faible sera déclenchée', verbose_name="seuil d'alerte de stock"),
        ),
        migrations.AddField(
            model_name='category',
            name='manage_stock',
            field=models.BooleanField(default=False, help_text='Si activé, vous pourrez gérer le stock pour cette catégorie', verbose_name='gérer le stock'),
        ),
        migrations.AddField(
            model_name='category',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantité totale en stock pour cette catégorie', verbose_name='quantité en stock'),
        ),
        migrations.AddField(
            model_name='category',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture de stock')], default='in_stock', max_length=20, verbose_name='état du stock'),
        ),
    ]
